//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx {
    public partial class Chat {
        protected global::System.Web.UI.WebControls.Literal litConversacion;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtPregunta;
        protected global::System.Web.UI.WebControls.Button btnEnviar;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
        protected global::System.Web.UI.WebControls.Literal litEndpoint;
        protected global::System.Web.UI.WebControls.Literal litHealth;
    }
}
