//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx {
    public partial class Crawler {
        protected global::System.Web.UI.WebControls.TextBox txtUrl;
        protected global::System.Web.UI.WebControls.TextBox txtMaxPages;
        protected global::System.Web.UI.WebControls.TextBox txtMaxDepth;
        protected global::System.Web.UI.UpdatePanel updControl;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Button btnIniciar;
        protected global::System.Web.UI.WebControls.Button btnParar;
        protected global::System.Web.UI.UpdatePanel updEstado;
        protected global::System.Web.UI.Timer tmrRefresco;
        protected global::System.Web.UI.WebControls.Literal litEstado;
        protected global::System.Web.UI.WebControls.Literal litFuentes;
        protected global::System.Web.UI.WebControls.Literal litLogs;
        protected global::System.Web.UI.WebControls.DropDownList ddlMode;
        protected global::System.Web.UI.WebControls.TextBox txtIntervalHours;
        protected global::System.Web.UI.WebControls.TextBox txtDailyTime;
        protected global::System.Web.UI.WebControls.CheckBox chkSchedCrawl;
        protected global::System.Web.UI.WebControls.CheckBox chkSchedIndex;
        protected global::System.Web.UI.WebControls.Label lblScheduler;
        protected global::System.Web.UI.WebControls.Button btnGuardarScheduler;
    }
}
