//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx
{
    public partial class _Default
    {
        /// <summary>
        /// txtUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUrl;

        /// <summary>
        /// txtCarpeta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCarpeta;

        /// <summary>
        /// txtMaxPages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMaxPages;

        /// <summary>
        /// txtMaxDepth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMaxDepth;

        /// <summary>
        /// chkFullCrawl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkFullCrawl;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// btnCrawl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCrawl;
    }
}
