//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx
{
    public partial class Evaluacion
    {
        protected global::System.Web.UI.UpdatePanel updControl;
        protected global::System.Web.UI.UpdatePanel updResults;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Button btnEvaluar;
        protected global::System.Web.UI.Timer tmrPoll;
        protected global::System.Web.UI.WebControls.PlaceHolder phProgress;
        protected global::System.Web.UI.WebControls.PlaceHolder phMetrics;
        protected global::System.Web.UI.WebControls.PlaceHolder phCategoryTable;
        protected global::System.Web.UI.WebControls.PlaceHolder phDifficultyTable;
        protected global::System.Web.UI.WebControls.PlaceHolder phFullResults;
    }
}
