//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx {
    public partial class Indexar {
        protected global::System.Web.UI.WebControls.DropDownList ddlCarpeta;
        protected global::System.Web.UI.WebControls.TextBox txtCarpetaCustom;
        protected global::System.Web.UI.WebControls.CheckBox chkRecursivo;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Button btnIndexar;
        protected global::System.Web.UI.WebControls.PlaceHolder phResumen;
        protected global::System.Web.UI.WebControls.Literal litResumen;
    }
}
