//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx {
    public partial class Indexar {
        protected global::System.Web.UI.UpdatePanel updIndexControl;
        protected global::System.Web.UI.WebControls.Label lblIndexMsg;
        protected global::System.Web.UI.WebControls.Button btnIniciarIndex;
        protected global::System.Web.UI.WebControls.Button btnPararIndex;
        protected global::System.Web.UI.UpdatePanel updIndexEstado;
        protected global::System.Web.UI.Timer tmrIndex;
        protected global::System.Web.UI.WebControls.Literal litIndexEstado;
        protected global::System.Web.UI.WebControls.Literal litIndexLogs;
        protected global::System.Web.UI.UpdatePanel updVectorizarControl;
        protected global::System.Web.UI.WebControls.Label lblVectorizarMsg;
        protected global::System.Web.UI.WebControls.Button btnVectorizar;
        protected global::System.Web.UI.UpdatePanel updVectorizarEstado;
        protected global::System.Web.UI.Timer tmrVectorizar;
        protected global::System.Web.UI.WebControls.PlaceHolder phVectorizarProgress;
        protected global::System.Web.UI.WebControls.DropDownList ddlCarpeta;
        protected global::System.Web.UI.WebControls.TextBox txtCarpetaCustom;
        protected global::System.Web.UI.WebControls.CheckBox chkRecursivo;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Button btnIndexar;
        protected global::System.Web.UI.WebControls.PlaceHolder phResumen;
        protected global::System.Web.UI.WebControls.Literal litResumen;
    }
}
