//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rag_can_aspx
{
    public partial class Resultados
    {
        protected global::System.Web.UI.WebControls.PlaceHolder phError;

        protected global::System.Web.UI.WebControls.Literal litError;

        protected global::System.Web.UI.WebControls.PlaceHolder phSuccess;

        protected global::System.Web.UI.WebControls.Literal litCarpeta;

        protected global::System.Web.UI.WebControls.Literal litResultados;
    }
}
